name: Finivo Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # 3. Set up gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "jovial-acronym-476213-q0"

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t asia-south1-docker.pkg.dev/jovial-acronym-476213-q0/finivo-repo/finivo-backend:latest \
            .

      # 5. Authenticate Docker to Artifact Registry
      - name: Docker auth
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      # 6. Push Docker image
      - name: Push Image
        run: |
          docker push asia-south1-docker.pkg.dev/jovial-acronym-476213-q0/finivo-repo/finivo-backend:latest

      # 7. Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy finivo-backend \
            --image asia-south1-docker.pkg.dev/jovial-acronym-476213-q0/finivo-repo/finivo-backend:latest \
            --project jovial-acronym-476213-q0 \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated \
            --set-secrets="DATABASE_URL=DATABASE_URL:latest" \
            --add-cloudsql-instances="jovial-acronym-476213-q0:asia-south1:finivo-db" \
            --memory=2Gi
